name: validate

on:
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: NPM Install
        run: npm install
      # - name: Check Linting
      #   run: npm run check:linting
      - name: Check Formatting
        run: npm run check:formatting
      - name: Check TS Compiles
        run: npm run check:typescript
